### ISSUE TITLE
Nova versão

### ISSUE THREAD

**Issue by israelkitz** [ricardo0877/aliscript#4] opened 2021-05-09 23:49 UTC
Oi, fui tentar rodar hoje (09/05) e aparentemente na hora que abre o navegador e começa a criar a conta ele dá um bug e para o programa.

--------------------------------------------------------
DevTools listening on ws://127.0.0.1:59361/devtools/browser/d9968750-5580-40bd-a725-de155befa7f3
[10952:8876:0509/204913.368:ERROR:device_event_log_impl.cc(214)] [20:49:13.355] Bluetooth: bluetooth_adapter_winrt.cc:1072 Getting Default Adapter failed.
[3096:9240:0509/204920.232:ERROR:socket_manager.cc(128)] Failed to resolve address for x., errorcode: -105
[3096:9240:0509/204920.260:ERROR:socket_manager.cc(128)] Failed to resolve address for x., errorcode: -105
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\aliscript-main\alibot.py", line 58, in <module>
    bot()
  File "C:\Users\WDAGUtilityAccount\Desktop\aliscript-main\alibot.py", line 27, in bot
    ActionChains(driver).move_to_element(slash_button).click(slash_button)
UnboundLocalError: local variable 'slash_button' referenced before assignment
-----------------------------------------------------------

Sabe dizer como resolver? e se possível, vai ter novas versões? obg

**Comment by rcorrei4** [comment] 2021-05-13 17:57
Closing as a duplicate of #2

**Closed as completed** 2021-05-13 17:57 UTC
